// admin.proto — meshctl → local meshd. Requires a client cert with the admin
// role (SAN URI lcm://<mesh_id>/admin/<name>), minted by `meshctl init`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: lcm/v1/admin.proto

package lcmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePairingCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtlSeconds    uint32                 `protobuf:"varint,1,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = server default (60)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePairingCodeRequest) Reset() {
	*x = CreatePairingCodeRequest{}
	mi := &file_lcm_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePairingCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePairingCodeRequest) ProtoMessage() {}

func (x *CreatePairingCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePairingCodeRequest.ProtoReflect.Descriptor instead.
func (*CreatePairingCodeRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePairingCodeRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreatePairingCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 8 digits
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PairAddr      string                 `protobuf:"bytes,3,opt,name=pair_addr,json=pairAddr,proto3" json:"pair_addr,omitempty"` // host:port of the PairingService listener
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePairingCodeResponse) Reset() {
	*x = CreatePairingCodeResponse{}
	mi := &file_lcm_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePairingCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePairingCodeResponse) ProtoMessage() {}

func (x *CreatePairingCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePairingCodeResponse.ProtoReflect.Descriptor instead.
func (*CreatePairingCodeResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePairingCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePairingCodeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreatePairingCodeResponse) GetPairAddr() string {
	if x != nil {
		return x.PairAddr
	}
	return ""
}

var File_lcm_v1_admin_proto protoreflect.FileDescriptor

const file_lcm_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x12lcm/v1/admin.proto\x12\x06lcm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x18CreatePairingCodeRequest\x12\x1f\n" +
	"\vttl_seconds\x18\x01 \x01(\rR\n" +
	"ttlSeconds\"\x87\x01\n" +
	"\x19CreatePairingCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\tpair_addr\x18\x03 \x01(\tR\bpairAddr2h\n" +
	"\fAdminService\x12X\n" +
	"\x11CreatePairingCode\x12 .lcm.v1.CreatePairingCodeRequest\x1a!.lcm.v1.CreatePairingCodeResponseB3Z1github.com/sanj6y/compute-mesh/proto/lcm/v1;lcmv1b\x06proto3"

var (
	file_lcm_v1_admin_proto_rawDescOnce sync.Once
	file_lcm_v1_admin_proto_rawDescData []byte
)

func file_lcm_v1_admin_proto_rawDescGZIP() []byte {
	file_lcm_v1_admin_proto_rawDescOnce.Do(func() {
		file_lcm_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lcm_v1_admin_proto_rawDesc), len(file_lcm_v1_admin_proto_rawDesc)))
	})
	return file_lcm_v1_admin_proto_rawDescData
}

var file_lcm_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lcm_v1_admin_proto_goTypes = []any{
	(*CreatePairingCodeRequest)(nil),  // 0: lcm.v1.CreatePairingCodeRequest
	(*CreatePairingCodeResponse)(nil), // 1: lcm.v1.CreatePairingCodeResponse
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
}
var file_lcm_v1_admin_proto_depIdxs = []int32{
	2, // 0: lcm.v1.CreatePairingCodeResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: lcm.v1.AdminService.CreatePairingCode:input_type -> lcm.v1.CreatePairingCodeRequest
	1, // 2: lcm.v1.AdminService.CreatePairingCode:output_type -> lcm.v1.CreatePairingCodeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lcm_v1_admin_proto_init() }
func file_lcm_v1_admin_proto_init() {
	if File_lcm_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lcm_v1_admin_proto_rawDesc), len(file_lcm_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lcm_v1_admin_proto_goTypes,
		DependencyIndexes: file_lcm_v1_admin_proto_depIdxs,
		MessageInfos:      file_lcm_v1_admin_proto_msgTypes,
	}.Build()
	File_lcm_v1_admin_proto = out.File
	file_lcm_v1_admin_proto_goTypes = nil
	file_lcm_v1_admin_proto_depIdxs = nil
}
