// inference.proto — coordinator/gateway → worker data plane and worker control.
//
// The gateway proxies Generate chunks to the client as SSE. On worker death
// the gateway re-dispatches with `prefix` set to the text already streamed,
// so the new worker continues rather than restarts (see docs/adr on failover).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: lcm/v1/inference.proto

package lcmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_SYSTEM      Role = 1
	Role_ROLE_USER        Role = 2
	Role_ROLE_ASSISTANT   Role = 3
	Role_ROLE_TOOL        Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_SYSTEM",
		2: "ROLE_USER",
		3: "ROLE_ASSISTANT",
		4: "ROLE_TOOL",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_SYSTEM":      1,
		"ROLE_USER":        2,
		"ROLE_ASSISTANT":   3,
		"ROLE_TOOL":        4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_lcm_v1_inference_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_lcm_v1_inference_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{0}
}

type FinishReason int32

const (
	FinishReason_FINISH_REASON_UNSPECIFIED FinishReason = 0
	FinishReason_FINISH_REASON_STOP        FinishReason = 1 // model emitted EOS or a stop sequence
	FinishReason_FINISH_REASON_LENGTH      FinishReason = 2 // hit max_tokens
	FinishReason_FINISH_REASON_ERROR       FinishReason = 3 // backend error; message in `error`
)

// Enum value maps for FinishReason.
var (
	FinishReason_name = map[int32]string{
		0: "FINISH_REASON_UNSPECIFIED",
		1: "FINISH_REASON_STOP",
		2: "FINISH_REASON_LENGTH",
		3: "FINISH_REASON_ERROR",
	}
	FinishReason_value = map[string]int32{
		"FINISH_REASON_UNSPECIFIED": 0,
		"FINISH_REASON_STOP":        1,
		"FINISH_REASON_LENGTH":      2,
		"FINISH_REASON_ERROR":       3,
	}
)

func (x FinishReason) Enum() *FinishReason {
	p := new(FinishReason)
	*p = x
	return p
}

func (x FinishReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinishReason) Descriptor() protoreflect.EnumDescriptor {
	return file_lcm_v1_inference_proto_enumTypes[1].Descriptor()
}

func (FinishReason) Type() protoreflect.EnumType {
	return &file_lcm_v1_inference_proto_enumTypes[1]
}

func (x FinishReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinishReason.Descriptor instead.
func (FinishReason) EnumDescriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=lcm.v1.Role" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_lcm_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenerateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // gateway-assigned; stable across failover
	Model     string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Exactly one of messages (chat) or prompt (raw completion) is set.
	Messages []*Message `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Prompt   string     `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// prefix is text already generated by a previous worker for this request_id.
	// The worker must condition on prompt+prefix and emit only continuation.
	Prefix        string   `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	MaxTokens     uint32   `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // remaining budget; gateway subtracts len(prefix)
	Temperature   float64  `protobuf:"fixed64,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP          float64  `protobuf:"fixed64,8,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	Seed          int64    `protobuf:"varint,9,opt,name=seed,proto3" json:"seed,omitempty"` // set by gateway so failover decoding is as close as possible
	Stop          []string `protobuf:"bytes,10,rep,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_lcm_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GenerateRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *GenerateRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *GenerateRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

type GenerateChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                                               // delta, not cumulative
	Tokens        uint32                 `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`                                                          // number of tokens in this delta (usually 1)
	FinishReason  FinishReason           `protobuf:"varint,3,opt,name=finish_reason,json=finishReason,proto3,enum=lcm.v1.FinishReason" json:"finish_reason,omitempty"` // set only on the final chunk
	Usage         *Usage                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`                                                             // set only on the final chunk
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateChunk) Reset() {
	*x = GenerateChunk{}
	mi := &file_lcm_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChunk) ProtoMessage() {}

func (x *GenerateChunk) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChunk.ProtoReflect.Descriptor instead.
func (*GenerateChunk) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateChunk) GetTokens() uint32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *GenerateChunk) GetFinishReason() FinishReason {
	if x != nil {
		return x.FinishReason
	}
	return FinishReason_FINISH_REASON_UNSPECIFIED
}

func (x *GenerateChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GenerateChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     uint32                 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32                 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_lcm_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Inputs        []string               `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_lcm_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedRequest) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_lcm_v1_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{5}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"` // same order as inputs
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_lcm_v1_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbedResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_lcm_v1_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{7}
}

func (x *LoadModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     uint64                 `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_lcm_v1_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{8}
}

func (x *LoadModelResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_lcm_v1_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{9}
}

func (x *UnloadModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_lcm_v1_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{10}
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_lcm_v1_inference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{11}
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InFlight      uint32                 `protobuf:"varint,1,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_lcm_v1_inference_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_inference_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_inference_proto_rawDescGZIP(), []int{12}
}

func (x *DrainResponse) GetInFlight() uint32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

var File_lcm_v1_inference_proto protoreflect.FileDescriptor

const file_lcm_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x16lcm/v1/inference.proto\x12\x06lcm.v1\"E\n" +
	"\aMessage\x12 \n" +
	"\x04role\x18\x01 \x01(\x0e2\f.lcm.v1.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xa1\x02\n" +
	"\x0fGenerateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12+\n" +
	"\bmessages\x18\x03 \x03(\v2\x0f.lcm.v1.MessageR\bmessages\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\rR\tmaxTokens\x12 \n" +
	"\vtemperature\x18\a \x01(\x01R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\b \x01(\x01R\x04topP\x12\x12\n" +
	"\x04seed\x18\t \x01(\x03R\x04seed\x12\x12\n" +
	"\x04stop\x18\n" +
	" \x03(\tR\x04stop\"\xb1\x01\n" +
	"\rGenerateChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\rR\x06tokens\x129\n" +
	"\rfinish_reason\x18\x03 \x01(\x0e2\x14.lcm.v1.FinishReasonR\ffinishReason\x12#\n" +
	"\x05usage\x18\x04 \x01(\v2\r.lcm.v1.UsageR\x05usage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"Y\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\rR\x10completionTokens\"[\n" +
	"\fEmbedRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06inputs\x18\x03 \x03(\tR\x06inputs\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"g\n" +
	"\rEmbedResponse\x121\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x11.lcm.v1.EmbeddingR\n" +
	"embeddings\x12#\n" +
	"\x05usage\x18\x02 \x01(\v2\r.lcm.v1.UsageR\x05usage\"(\n" +
	"\x10LoadModelRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"2\n" +
	"\x11LoadModelResponse\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x04R\tsizeBytes\"*\n" +
	"\x12UnloadModelRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"\x15\n" +
	"\x13UnloadModelResponse\"\x0e\n" +
	"\fDrainRequest\",\n" +
	"\rDrainResponse\x12\x1b\n" +
	"\tin_flight\x18\x01 \x01(\rR\binFlight*_\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x01\x12\r\n" +
	"\tROLE_USER\x10\x02\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x03\x12\r\n" +
	"\tROLE_TOOL\x10\x04*x\n" +
	"\fFinishReason\x12\x1d\n" +
	"\x19FINISH_REASON_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FINISH_REASON_STOP\x10\x01\x12\x18\n" +
	"\x14FINISH_REASON_LENGTH\x10\x02\x12\x17\n" +
	"\x13FINISH_REASON_ERROR\x10\x032\xc6\x02\n" +
	"\x10InferenceService\x12<\n" +
	"\bGenerate\x12\x17.lcm.v1.GenerateRequest\x1a\x15.lcm.v1.GenerateChunk0\x01\x124\n" +
	"\x05Embed\x12\x14.lcm.v1.EmbedRequest\x1a\x15.lcm.v1.EmbedResponse\x12@\n" +
	"\tLoadModel\x12\x18.lcm.v1.LoadModelRequest\x1a\x19.lcm.v1.LoadModelResponse\x12F\n" +
	"\vUnloadModel\x12\x1a.lcm.v1.UnloadModelRequest\x1a\x1b.lcm.v1.UnloadModelResponse\x124\n" +
	"\x05Drain\x12\x14.lcm.v1.DrainRequest\x1a\x15.lcm.v1.DrainResponseB3Z1github.com/sanj6y/compute-mesh/proto/lcm/v1;lcmv1b\x06proto3"

var (
	file_lcm_v1_inference_proto_rawDescOnce sync.Once
	file_lcm_v1_inference_proto_rawDescData []byte
)

func file_lcm_v1_inference_proto_rawDescGZIP() []byte {
	file_lcm_v1_inference_proto_rawDescOnce.Do(func() {
		file_lcm_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lcm_v1_inference_proto_rawDesc), len(file_lcm_v1_inference_proto_rawDesc)))
	})
	return file_lcm_v1_inference_proto_rawDescData
}

var file_lcm_v1_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lcm_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lcm_v1_inference_proto_goTypes = []any{
	(Role)(0),                   // 0: lcm.v1.Role
	(FinishReason)(0),           // 1: lcm.v1.FinishReason
	(*Message)(nil),             // 2: lcm.v1.Message
	(*GenerateRequest)(nil),     // 3: lcm.v1.GenerateRequest
	(*GenerateChunk)(nil),       // 4: lcm.v1.GenerateChunk
	(*Usage)(nil),               // 5: lcm.v1.Usage
	(*EmbedRequest)(nil),        // 6: lcm.v1.EmbedRequest
	(*Embedding)(nil),           // 7: lcm.v1.Embedding
	(*EmbedResponse)(nil),       // 8: lcm.v1.EmbedResponse
	(*LoadModelRequest)(nil),    // 9: lcm.v1.LoadModelRequest
	(*LoadModelResponse)(nil),   // 10: lcm.v1.LoadModelResponse
	(*UnloadModelRequest)(nil),  // 11: lcm.v1.UnloadModelRequest
	(*UnloadModelResponse)(nil), // 12: lcm.v1.UnloadModelResponse
	(*DrainRequest)(nil),        // 13: lcm.v1.DrainRequest
	(*DrainResponse)(nil),       // 14: lcm.v1.DrainResponse
}
var file_lcm_v1_inference_proto_depIdxs = []int32{
	0,  // 0: lcm.v1.Message.role:type_name -> lcm.v1.Role
	2,  // 1: lcm.v1.GenerateRequest.messages:type_name -> lcm.v1.Message
	1,  // 2: lcm.v1.GenerateChunk.finish_reason:type_name -> lcm.v1.FinishReason
	5,  // 3: lcm.v1.GenerateChunk.usage:type_name -> lcm.v1.Usage
	7,  // 4: lcm.v1.EmbedResponse.embeddings:type_name -> lcm.v1.Embedding
	5,  // 5: lcm.v1.EmbedResponse.usage:type_name -> lcm.v1.Usage
	3,  // 6: lcm.v1.InferenceService.Generate:input_type -> lcm.v1.GenerateRequest
	6,  // 7: lcm.v1.InferenceService.Embed:input_type -> lcm.v1.EmbedRequest
	9,  // 8: lcm.v1.InferenceService.LoadModel:input_type -> lcm.v1.LoadModelRequest
	11, // 9: lcm.v1.InferenceService.UnloadModel:input_type -> lcm.v1.UnloadModelRequest
	13, // 10: lcm.v1.InferenceService.Drain:input_type -> lcm.v1.DrainRequest
	4,  // 11: lcm.v1.InferenceService.Generate:output_type -> lcm.v1.GenerateChunk
	8,  // 12: lcm.v1.InferenceService.Embed:output_type -> lcm.v1.EmbedResponse
	10, // 13: lcm.v1.InferenceService.LoadModel:output_type -> lcm.v1.LoadModelResponse
	12, // 14: lcm.v1.InferenceService.UnloadModel:output_type -> lcm.v1.UnloadModelResponse
	14, // 15: lcm.v1.InferenceService.Drain:output_type -> lcm.v1.DrainResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_lcm_v1_inference_proto_init() }
func file_lcm_v1_inference_proto_init() {
	if File_lcm_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lcm_v1_inference_proto_rawDesc), len(file_lcm_v1_inference_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lcm_v1_inference_proto_goTypes,
		DependencyIndexes: file_lcm_v1_inference_proto_depIdxs,
		EnumInfos:         file_lcm_v1_inference_proto_enumTypes,
		MessageInfos:      file_lcm_v1_inference_proto_msgTypes,
	}.Build()
	File_lcm_v1_inference_proto = out.File
	file_lcm_v1_inference_proto_goTypes = nil
	file_lcm_v1_inference_proto_depIdxs = nil
}
