// node.proto — worker ⇄ coordinator control plane.
//
// Workers dial the coordinator over mTLS, register once, then hold a
// long-lived client stream of TelemetrySample messages (1 s cadence).
// The coordinator never pushes on this stream; coordinator → worker
// commands (load/unload/drain) live in inference.proto because the
// coordinator already dials workers for Generate.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: lcm/v1/node.proto

package lcmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeInfo is the static-ish description of a worker. Anything that changes
// every second belongs in TelemetrySample instead.
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable identifier, matches the cert's SAN URI
	MeshId        string                 `protobuf:"bytes,2,opt,name=mesh_id,json=meshId,proto3" json:"mesh_id,omitempty"` // pairing domain; connections to a foreign mesh_id are refused
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,4,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"` // host:port the coordinator dials for InferenceService
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                   // meshd build version
	Backends      []string               `protobuf:"bytes,6,rep,name=backends,proto3" json:"backends,omitempty"`                 // "llamacpp", "ollama", "vllm", "fake"
	Gpu           *GpuInfo               `protobuf:"bytes,7,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"` // free-form, e.g. "trusted:home" for privacy filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_lcm_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_lcm_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetMeshId() string {
	if x != nil {
		return x.MeshId
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *NodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeInfo) GetBackends() []string {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *NodeInfo) GetGpu() *GpuInfo {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *NodeInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GpuInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Vendor         string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"` // "nvidia", "apple", "none"
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`     // "RTX 4090", "Apple M3 Max"
	Count          uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	VramTotalBytes uint64                 `protobuf:"varint,4,opt,name=vram_total_bytes,json=vramTotalBytes,proto3" json:"vram_total_bytes,omitempty"` // unified memory on Apple Silicon
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GpuInfo) Reset() {
	*x = GpuInfo{}
	mi := &file_lcm_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuInfo) ProtoMessage() {}

func (x *GpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuInfo.ProtoReflect.Descriptor instead.
func (*GpuInfo) Descriptor() ([]byte, []int) {
	return file_lcm_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *GpuInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GpuInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GpuInfo) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GpuInfo) GetVramTotalBytes() uint64 {
	if x != nil {
		return x.VramTotalBytes
	}
	return 0
}

// ModelInfo describes one model a worker can serve.
type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // e.g. "llama-3.1-8b-instruct"
	Quant         string                 `protobuf:"bytes,2,opt,name=quant,proto3" json:"quant,omitempty"`                           // e.g. "Q4_K_M"
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // weights on disk; used for headroom filter
	Resident      bool                   `protobuf:"varint,4,opt,name=resident,proto3" json:"resident,omitempty"`                    // true if weights are loaded in VRAM right now
	Backend       string                 `protobuf:"bytes,5,opt,name=backend,proto3" json:"backend,omitempty"`
	LastUsed      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_lcm_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_lcm_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetQuant() string {
	if x != nil {
		return x.Quant
	}
	return ""
}

func (x *ModelInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ModelInfo) GetResident() bool {
	if x != nil {
		return x.Resident
	}
	return false
}

func (x *ModelInfo) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ModelInfo) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_lcm_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoordinatorId string                 `protobuf:"bytes,1,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	// telemetry_interval_ms lets the coordinator tune sampling cadence. Default 1000.
	TelemetryIntervalMs uint32 `protobuf:"varint,2,opt,name=telemetry_interval_ms,json=telemetryIntervalMs,proto3" json:"telemetry_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_lcm_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *RegisterResponse) GetTelemetryIntervalMs() uint32 {
	if x != nil {
		return x.TelemetryIntervalMs
	}
	return 0
}

// TelemetrySample is what the scheduler scores on. Keep it flat and cheap.
type TelemetrySample struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Ts     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	// memory
	VramTotalBytes uint64 `protobuf:"varint,3,opt,name=vram_total_bytes,json=vramTotalBytes,proto3" json:"vram_total_bytes,omitempty"`
	VramUsedBytes  uint64 `protobuf:"varint,4,opt,name=vram_used_bytes,json=vramUsedBytes,proto3" json:"vram_used_bytes,omitempty"`
	VramFreeBytes  uint64 `protobuf:"varint,5,opt,name=vram_free_bytes,json=vramFreeBytes,proto3" json:"vram_free_bytes,omitempty"`
	RamFreeBytes   uint64 `protobuf:"varint,6,opt,name=ram_free_bytes,json=ramFreeBytes,proto3" json:"ram_free_bytes,omitempty"`
	// models
	Models []*ModelInfo `protobuf:"bytes,7,rep,name=models,proto3" json:"models,omitempty"`
	// load
	QueueDepth   uint32  `protobuf:"varint,8,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`           // requests waiting on the backend
	InFlight     uint32  `protobuf:"varint,9,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`                 // requests currently generating
	TokensPerSec float64 `protobuf:"fixed64,10,opt,name=tokens_per_sec,json=tokensPerSec,proto3" json:"tokens_per_sec,omitempty"` // over last 10 s, all streams summed
	TtftP50Ms    float64 `protobuf:"fixed64,11,opt,name=ttft_p50_ms,json=ttftP50Ms,proto3" json:"ttft_p50_ms,omitempty"`          // over last 60 s
	TtftP99Ms    float64 `protobuf:"fixed64,12,opt,name=ttft_p99_ms,json=ttftP99Ms,proto3" json:"ttft_p99_ms,omitempty"`
	CpuLoad_1M   float64 `protobuf:"fixed64,13,opt,name=cpu_load_1m,json=cpuLoad1m,proto3" json:"cpu_load_1m,omitempty"` // normalized 0..1 per core
	// gpu
	GpuTempC  float64 `protobuf:"fixed64,14,opt,name=gpu_temp_c,json=gpuTempC,proto3" json:"gpu_temp_c,omitempty"`
	GpuPowerW float64 `protobuf:"fixed64,15,opt,name=gpu_power_w,json=gpuPowerW,proto3" json:"gpu_power_w,omitempty"`
	GpuUtil   float64 `protobuf:"fixed64,16,opt,name=gpu_util,json=gpuUtil,proto3" json:"gpu_util,omitempty"` // 0..1, NVML only
	// link
	RttToCoordinatorMs float64 `protobuf:"fixed64,17,opt,name=rtt_to_coordinator_ms,json=rttToCoordinatorMs,proto3" json:"rtt_to_coordinator_ms,omitempty"`
	// lifecycle
	Draining      bool `protobuf:"varint,18,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySample) Reset() {
	*x = TelemetrySample{}
	mi := &file_lcm_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySample) ProtoMessage() {}

func (x *TelemetrySample) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySample.ProtoReflect.Descriptor instead.
func (*TelemetrySample) Descriptor() ([]byte, []int) {
	return file_lcm_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetrySample) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetrySample) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *TelemetrySample) GetVramTotalBytes() uint64 {
	if x != nil {
		return x.VramTotalBytes
	}
	return 0
}

func (x *TelemetrySample) GetVramUsedBytes() uint64 {
	if x != nil {
		return x.VramUsedBytes
	}
	return 0
}

func (x *TelemetrySample) GetVramFreeBytes() uint64 {
	if x != nil {
		return x.VramFreeBytes
	}
	return 0
}

func (x *TelemetrySample) GetRamFreeBytes() uint64 {
	if x != nil {
		return x.RamFreeBytes
	}
	return 0
}

func (x *TelemetrySample) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *TelemetrySample) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *TelemetrySample) GetInFlight() uint32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *TelemetrySample) GetTokensPerSec() float64 {
	if x != nil {
		return x.TokensPerSec
	}
	return 0
}

func (x *TelemetrySample) GetTtftP50Ms() float64 {
	if x != nil {
		return x.TtftP50Ms
	}
	return 0
}

func (x *TelemetrySample) GetTtftP99Ms() float64 {
	if x != nil {
		return x.TtftP99Ms
	}
	return 0
}

func (x *TelemetrySample) GetCpuLoad_1M() float64 {
	if x != nil {
		return x.CpuLoad_1M
	}
	return 0
}

func (x *TelemetrySample) GetGpuTempC() float64 {
	if x != nil {
		return x.GpuTempC
	}
	return 0
}

func (x *TelemetrySample) GetGpuPowerW() float64 {
	if x != nil {
		return x.GpuPowerW
	}
	return 0
}

func (x *TelemetrySample) GetGpuUtil() float64 {
	if x != nil {
		return x.GpuUtil
	}
	return 0
}

func (x *TelemetrySample) GetRttToCoordinatorMs() float64 {
	if x != nil {
		return x.RttToCoordinatorMs
	}
	return 0
}

func (x *TelemetrySample) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type ReportTelemetryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SamplesReceived uint64                 `protobuf:"varint,1,opt,name=samples_received,json=samplesReceived,proto3" json:"samples_received,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportTelemetryResponse) Reset() {
	*x = ReportTelemetryResponse{}
	mi := &file_lcm_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTelemetryResponse) ProtoMessage() {}

func (x *ReportTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTelemetryResponse.ProtoReflect.Descriptor instead.
func (*ReportTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *ReportTelemetryResponse) GetSamplesReceived() uint64 {
	if x != nil {
		return x.SamplesReceived
	}
	return 0
}

var File_lcm_v1_node_proto protoreflect.FileDescriptor

const file_lcm_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x11lcm/v1/node.proto\x12\x06lcm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\amesh_id\x18\x02 \x01(\tR\x06meshId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1b\n" +
	"\tgrpc_addr\x18\x04 \x01(\tR\bgrpcAddr\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1a\n" +
	"\bbackends\x18\x06 \x03(\tR\bbackends\x12!\n" +
	"\x03gpu\x18\a \x01(\v2\x0f.lcm.v1.GpuInfoR\x03gpu\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"u\n" +
	"\aGpuInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12(\n" +
	"\x10vram_total_bytes\x18\x04 \x01(\x04R\x0evramTotalBytes\"\xc3\x01\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05quant\x18\x02 \x01(\tR\x05quant\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x1a\n" +
	"\bresident\x18\x04 \x01(\bR\bresident\x12\x18\n" +
	"\abackend\x18\x05 \x01(\tR\abackend\x127\n" +
	"\tlast_used\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\"7\n" +
	"\x0fRegisterRequest\x12$\n" +
	"\x04node\x18\x01 \x01(\v2\x10.lcm.v1.NodeInfoR\x04node\"m\n" +
	"\x10RegisterResponse\x12%\n" +
	"\x0ecoordinator_id\x18\x01 \x01(\tR\rcoordinatorId\x122\n" +
	"\x15telemetry_interval_ms\x18\x02 \x01(\rR\x13telemetryIntervalMs\"\x8d\x05\n" +
	"\x0fTelemetrySample\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12(\n" +
	"\x10vram_total_bytes\x18\x03 \x01(\x04R\x0evramTotalBytes\x12&\n" +
	"\x0fvram_used_bytes\x18\x04 \x01(\x04R\rvramUsedBytes\x12&\n" +
	"\x0fvram_free_bytes\x18\x05 \x01(\x04R\rvramFreeBytes\x12$\n" +
	"\x0eram_free_bytes\x18\x06 \x01(\x04R\framFreeBytes\x12)\n" +
	"\x06models\x18\a \x03(\v2\x11.lcm.v1.ModelInfoR\x06models\x12\x1f\n" +
	"\vqueue_depth\x18\b \x01(\rR\n" +
	"queueDepth\x12\x1b\n" +
	"\tin_flight\x18\t \x01(\rR\binFlight\x12$\n" +
	"\x0etokens_per_sec\x18\n" +
	" \x01(\x01R\ftokensPerSec\x12\x1e\n" +
	"\vttft_p50_ms\x18\v \x01(\x01R\tttftP50Ms\x12\x1e\n" +
	"\vttft_p99_ms\x18\f \x01(\x01R\tttftP99Ms\x12\x1e\n" +
	"\vcpu_load_1m\x18\r \x01(\x01R\tcpuLoad1m\x12\x1c\n" +
	"\n" +
	"gpu_temp_c\x18\x0e \x01(\x01R\bgpuTempC\x12\x1e\n" +
	"\vgpu_power_w\x18\x0f \x01(\x01R\tgpuPowerW\x12\x19\n" +
	"\bgpu_util\x18\x10 \x01(\x01R\agpuUtil\x121\n" +
	"\x15rtt_to_coordinator_ms\x18\x11 \x01(\x01R\x12rttToCoordinatorMs\x12\x1a\n" +
	"\bdraining\x18\x12 \x01(\bR\bdraining\"D\n" +
	"\x17ReportTelemetryResponse\x12)\n" +
	"\x10samples_received\x18\x01 \x01(\x04R\x0fsamplesReceived2\x9b\x01\n" +
	"\vNodeService\x12=\n" +
	"\bRegister\x12\x17.lcm.v1.RegisterRequest\x1a\x18.lcm.v1.RegisterResponse\x12M\n" +
	"\x0fReportTelemetry\x12\x17.lcm.v1.TelemetrySample\x1a\x1f.lcm.v1.ReportTelemetryResponse(\x01B3Z1github.com/sanj6y/compute-mesh/proto/lcm/v1;lcmv1b\x06proto3"

var (
	file_lcm_v1_node_proto_rawDescOnce sync.Once
	file_lcm_v1_node_proto_rawDescData []byte
)

func file_lcm_v1_node_proto_rawDescGZIP() []byte {
	file_lcm_v1_node_proto_rawDescOnce.Do(func() {
		file_lcm_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lcm_v1_node_proto_rawDesc), len(file_lcm_v1_node_proto_rawDesc)))
	})
	return file_lcm_v1_node_proto_rawDescData
}

var file_lcm_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lcm_v1_node_proto_goTypes = []any{
	(*NodeInfo)(nil),                // 0: lcm.v1.NodeInfo
	(*GpuInfo)(nil),                 // 1: lcm.v1.GpuInfo
	(*ModelInfo)(nil),               // 2: lcm.v1.ModelInfo
	(*RegisterRequest)(nil),         // 3: lcm.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 4: lcm.v1.RegisterResponse
	(*TelemetrySample)(nil),         // 5: lcm.v1.TelemetrySample
	(*ReportTelemetryResponse)(nil), // 6: lcm.v1.ReportTelemetryResponse
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_lcm_v1_node_proto_depIdxs = []int32{
	1, // 0: lcm.v1.NodeInfo.gpu:type_name -> lcm.v1.GpuInfo
	7, // 1: lcm.v1.ModelInfo.last_used:type_name -> google.protobuf.Timestamp
	0, // 2: lcm.v1.RegisterRequest.node:type_name -> lcm.v1.NodeInfo
	7, // 3: lcm.v1.TelemetrySample.ts:type_name -> google.protobuf.Timestamp
	2, // 4: lcm.v1.TelemetrySample.models:type_name -> lcm.v1.ModelInfo
	3, // 5: lcm.v1.NodeService.Register:input_type -> lcm.v1.RegisterRequest
	5, // 6: lcm.v1.NodeService.ReportTelemetry:input_type -> lcm.v1.TelemetrySample
	4, // 7: lcm.v1.NodeService.Register:output_type -> lcm.v1.RegisterResponse
	6, // 8: lcm.v1.NodeService.ReportTelemetry:output_type -> lcm.v1.ReportTelemetryResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_lcm_v1_node_proto_init() }
func file_lcm_v1_node_proto_init() {
	if File_lcm_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lcm_v1_node_proto_rawDesc), len(file_lcm_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lcm_v1_node_proto_goTypes,
		DependencyIndexes: file_lcm_v1_node_proto_depIdxs,
		MessageInfos:      file_lcm_v1_node_proto_msgTypes,
	}.Build()
	File_lcm_v1_node_proto = out.File
	file_lcm_v1_node_proto_goTypes = nil
	file_lcm_v1_node_proto_depIdxs = nil
}
