// pairing.proto — bootstrap a new node into the mesh with a one-time code.
//
// This is the only gRPC service that does not require a client certificate:
// the joiner has none yet. It is served on a dedicated listener with the
// coordinator's node cert (server-auth TLS). The joiner cannot verify that
// cert (it has no CA yet), so trust comes from the code instead:
//
//   K          = argon2id(code, salt)                      // slow, per-session salt
//   client_mac = HMAC(K, "lcm-pair-v1/client" || session || sha256(server_tls_cert) || csr)
//   server_mac = HMAC(K, "lcm-pair-v1/server" || session || ca_cert || node_cert)
//
// Binding the server's TLS cert into client_mac means a relay in the middle
// (presenting its own cert to the joiner) produces a MAC the real coordinator
// rejects. Argon2id makes offline brute force of the 8-digit code impractical
// inside the 60 s code lifetime. Codes are single-use; a session gets one
// attempt. See docs/adr/0002-pairing.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: lcm/v1/pairing.proto

package lcmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginPairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // informational; the CSR is authoritative
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPairingRequest) Reset() {
	*x = BeginPairingRequest{}
	mi := &file_lcm_v1_pairing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPairingRequest) ProtoMessage() {}

func (x *BeginPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_pairing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPairingRequest.ProtoReflect.Descriptor instead.
func (*BeginPairingRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_pairing_proto_rawDescGZIP(), []int{0}
}

func (x *BeginPairingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type BeginPairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 16 random bytes
	Salt          []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`                            // 16 random bytes, argon2id salt
	MeshId        string                 `protobuf:"bytes,3,opt,name=mesh_id,json=meshId,proto3" json:"mesh_id,omitempty"`          // also visible in the mDNS TXT record, so not secret
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPairingResponse) Reset() {
	*x = BeginPairingResponse{}
	mi := &file_lcm_v1_pairing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPairingResponse) ProtoMessage() {}

func (x *BeginPairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_pairing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPairingResponse.ProtoReflect.Descriptor instead.
func (*BeginPairingResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_pairing_proto_rawDescGZIP(), []int{1}
}

func (x *BeginPairingResponse) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *BeginPairingResponse) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *BeginPairingResponse) GetMeshId() string {
	if x != nil {
		return x.MeshId
	}
	return ""
}

func (x *BeginPairingResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CompletePairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CsrDer        []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`          // PKCS#10, CN = node_id, signed by the joiner's key
	ClientMac     []byte                 `protobuf:"bytes,3,opt,name=client_mac,json=clientMac,proto3" json:"client_mac,omitempty"` // see file comment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletePairingRequest) Reset() {
	*x = CompletePairingRequest{}
	mi := &file_lcm_v1_pairing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletePairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePairingRequest) ProtoMessage() {}

func (x *CompletePairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_pairing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePairingRequest.ProtoReflect.Descriptor instead.
func (*CompletePairingRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_pairing_proto_rawDescGZIP(), []int{2}
}

func (x *CompletePairingRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *CompletePairingRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *CompletePairingRequest) GetClientMac() []byte {
	if x != nil {
		return x.ClientMac
	}
	return nil
}

type CompletePairingResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CaCertDer           []byte                 `protobuf:"bytes,1,opt,name=ca_cert_der,json=caCertDer,proto3" json:"ca_cert_der,omitempty"`
	NodeCertDer         []byte                 `protobuf:"bytes,2,opt,name=node_cert_der,json=nodeCertDer,proto3" json:"node_cert_der,omitempty"`
	MeshId              string                 `protobuf:"bytes,3,opt,name=mesh_id,json=meshId,proto3" json:"mesh_id,omitempty"`
	CoordinatorNodeId   string                 `protobuf:"bytes,4,opt,name=coordinator_node_id,json=coordinatorNodeId,proto3" json:"coordinator_node_id,omitempty"`
	CoordinatorGrpcAddr string                 `protobuf:"bytes,5,opt,name=coordinator_grpc_addr,json=coordinatorGrpcAddr,proto3" json:"coordinator_grpc_addr,omitempty"` // host:port for NodeService
	ServerMac           []byte                 `protobuf:"bytes,6,opt,name=server_mac,json=serverMac,proto3" json:"server_mac,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompletePairingResponse) Reset() {
	*x = CompletePairingResponse{}
	mi := &file_lcm_v1_pairing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletePairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePairingResponse) ProtoMessage() {}

func (x *CompletePairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_pairing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePairingResponse.ProtoReflect.Descriptor instead.
func (*CompletePairingResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_pairing_proto_rawDescGZIP(), []int{3}
}

func (x *CompletePairingResponse) GetCaCertDer() []byte {
	if x != nil {
		return x.CaCertDer
	}
	return nil
}

func (x *CompletePairingResponse) GetNodeCertDer() []byte {
	if x != nil {
		return x.NodeCertDer
	}
	return nil
}

func (x *CompletePairingResponse) GetMeshId() string {
	if x != nil {
		return x.MeshId
	}
	return ""
}

func (x *CompletePairingResponse) GetCoordinatorNodeId() string {
	if x != nil {
		return x.CoordinatorNodeId
	}
	return ""
}

func (x *CompletePairingResponse) GetCoordinatorGrpcAddr() string {
	if x != nil {
		return x.CoordinatorGrpcAddr
	}
	return ""
}

func (x *CompletePairingResponse) GetServerMac() []byte {
	if x != nil {
		return x.ServerMac
	}
	return nil
}

var File_lcm_v1_pairing_proto protoreflect.FileDescriptor

const file_lcm_v1_pairing_proto_rawDesc = "" +
	"\n" +
	"\x14lcm/v1/pairing.proto\x12\x06lcm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x13BeginPairingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x9d\x01\n" +
	"\x14BeginPairingResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\x12\x17\n" +
	"\amesh_id\x18\x03 \x01(\tR\x06meshId\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"o\n" +
	"\x16CompletePairingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x1d\n" +
	"\n" +
	"client_mac\x18\x03 \x01(\fR\tclientMac\"\xf9\x01\n" +
	"\x17CompletePairingResponse\x12\x1e\n" +
	"\vca_cert_der\x18\x01 \x01(\fR\tcaCertDer\x12\"\n" +
	"\rnode_cert_der\x18\x02 \x01(\fR\vnodeCertDer\x12\x17\n" +
	"\amesh_id\x18\x03 \x01(\tR\x06meshId\x12.\n" +
	"\x13coordinator_node_id\x18\x04 \x01(\tR\x11coordinatorNodeId\x122\n" +
	"\x15coordinator_grpc_addr\x18\x05 \x01(\tR\x13coordinatorGrpcAddr\x12\x1d\n" +
	"\n" +
	"server_mac\x18\x06 \x01(\fR\tserverMac2\xa1\x01\n" +
	"\x0ePairingService\x12B\n" +
	"\x05Begin\x12\x1b.lcm.v1.BeginPairingRequest\x1a\x1c.lcm.v1.BeginPairingResponse\x12K\n" +
	"\bComplete\x12\x1e.lcm.v1.CompletePairingRequest\x1a\x1f.lcm.v1.CompletePairingResponseB3Z1github.com/sanj6y/compute-mesh/proto/lcm/v1;lcmv1b\x06proto3"

var (
	file_lcm_v1_pairing_proto_rawDescOnce sync.Once
	file_lcm_v1_pairing_proto_rawDescData []byte
)

func file_lcm_v1_pairing_proto_rawDescGZIP() []byte {
	file_lcm_v1_pairing_proto_rawDescOnce.Do(func() {
		file_lcm_v1_pairing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lcm_v1_pairing_proto_rawDesc), len(file_lcm_v1_pairing_proto_rawDesc)))
	})
	return file_lcm_v1_pairing_proto_rawDescData
}

var file_lcm_v1_pairing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lcm_v1_pairing_proto_goTypes = []any{
	(*BeginPairingRequest)(nil),     // 0: lcm.v1.BeginPairingRequest
	(*BeginPairingResponse)(nil),    // 1: lcm.v1.BeginPairingResponse
	(*CompletePairingRequest)(nil),  // 2: lcm.v1.CompletePairingRequest
	(*CompletePairingResponse)(nil), // 3: lcm.v1.CompletePairingResponse
	(*timestamppb.Timestamp)(nil),   // 4: google.protobuf.Timestamp
}
var file_lcm_v1_pairing_proto_depIdxs = []int32{
	4, // 0: lcm.v1.BeginPairingResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: lcm.v1.PairingService.Begin:input_type -> lcm.v1.BeginPairingRequest
	2, // 2: lcm.v1.PairingService.Complete:input_type -> lcm.v1.CompletePairingRequest
	1, // 3: lcm.v1.PairingService.Begin:output_type -> lcm.v1.BeginPairingResponse
	3, // 4: lcm.v1.PairingService.Complete:output_type -> lcm.v1.CompletePairingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lcm_v1_pairing_proto_init() }
func file_lcm_v1_pairing_proto_init() {
	if File_lcm_v1_pairing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lcm_v1_pairing_proto_rawDesc), len(file_lcm_v1_pairing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lcm_v1_pairing_proto_goTypes,
		DependencyIndexes: file_lcm_v1_pairing_proto_depIdxs,
		MessageInfos:      file_lcm_v1_pairing_proto_msgTypes,
	}.Build()
	File_lcm_v1_pairing_proto = out.File
	file_lcm_v1_pairing_proto_goTypes = nil
	file_lcm_v1_pairing_proto_depIdxs = nil
}
