// pairing.proto — bootstrap a new node into the mesh with a one-time code.
//
// This is the only gRPC service that does not require a client certificate:
// the joiner has none yet. It is served on a dedicated listener with the
// coordinator's node cert (server-auth TLS). The joiner cannot verify that
// cert (it has no CA yet), so trust comes from the code instead:
//
//   K          = argon2id(code, salt)                      // slow, per-session salt
//   client_mac = HMAC(K, "lcm-pair-v1/client" || session || sha256(server_tls_cert) || csr)
//   server_mac = HMAC(K, "lcm-pair-v1/server" || session || ca_cert || node_cert)
//
// Binding the server's TLS cert into client_mac means a relay in the middle
// (presenting its own cert to the joiner) produces a MAC the real coordinator
// rejects. Argon2id makes offline brute force of the 8-digit code impractical
// inside the 60 s code lifetime. Codes are single-use; a session gets one
// attempt. See docs/adr/0002-pairing.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: lcm/v1/pairing.proto

package lcmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PairingService_Begin_FullMethodName    = "/lcm.v1.PairingService/Begin"
	PairingService_Complete_FullMethodName = "/lcm.v1.PairingService/Complete"
)

// PairingServiceClient is the client API for PairingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PairingServiceClient interface {
	// Begin opens a pairing session and returns the KDF salt.
	Begin(ctx context.Context, in *BeginPairingRequest, opts ...grpc.CallOption) (*BeginPairingResponse, error)
	// Complete submits the code-bound CSR and returns the signed bundle.
	Complete(ctx context.Context, in *CompletePairingRequest, opts ...grpc.CallOption) (*CompletePairingResponse, error)
}

type pairingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPairingServiceClient(cc grpc.ClientConnInterface) PairingServiceClient {
	return &pairingServiceClient{cc}
}

func (c *pairingServiceClient) Begin(ctx context.Context, in *BeginPairingRequest, opts ...grpc.CallOption) (*BeginPairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginPairingResponse)
	err := c.cc.Invoke(ctx, PairingService_Begin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pairingServiceClient) Complete(ctx context.Context, in *CompletePairingRequest, opts ...grpc.CallOption) (*CompletePairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletePairingResponse)
	err := c.cc.Invoke(ctx, PairingService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PairingServiceServer is the server API for PairingService service.
// All implementations must embed UnimplementedPairingServiceServer
// for forward compatibility.
type PairingServiceServer interface {
	// Begin opens a pairing session and returns the KDF salt.
	Begin(context.Context, *BeginPairingRequest) (*BeginPairingResponse, error)
	// Complete submits the code-bound CSR and returns the signed bundle.
	Complete(context.Context, *CompletePairingRequest) (*CompletePairingResponse, error)
	mustEmbedUnimplementedPairingServiceServer()
}

// UnimplementedPairingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPairingServiceServer struct{}

func (UnimplementedPairingServiceServer) Begin(context.Context, *BeginPairingRequest) (*BeginPairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedPairingServiceServer) Complete(context.Context, *CompletePairingRequest) (*CompletePairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedPairingServiceServer) mustEmbedUnimplementedPairingServiceServer() {}
func (UnimplementedPairingServiceServer) testEmbeddedByValue()                        {}

// UnsafePairingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PairingServiceServer will
// result in compilation errors.
type UnsafePairingServiceServer interface {
	mustEmbedUnimplementedPairingServiceServer()
}

func RegisterPairingServiceServer(s grpc.ServiceRegistrar, srv PairingServiceServer) {
	// If the following call panics, it indicates UnimplementedPairingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PairingService_ServiceDesc, srv)
}

func _PairingService_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServiceServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PairingService_Begin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServiceServer).Begin(ctx, req.(*BeginPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PairingService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PairingService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServiceServer).Complete(ctx, req.(*CompletePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PairingService_ServiceDesc is the grpc.ServiceDesc for PairingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PairingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lcm.v1.PairingService",
	HandlerType: (*PairingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _PairingService_Begin_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _PairingService_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcm/v1/pairing.proto",
}
