// scheduler.proto — gateway → coordinator placement API and meshctl status.
//
// In v1 the gateway and coordinator usually share a process and call the
// scheduler in-memory; this service is the boundary for running them apart
// and for `meshctl status` / `meshctl models`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: lcm/v1/scheduler.proto

package lcmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_OP_UNSPECIFIED Op = 0
	Op_OP_CHAT        Op = 1
	Op_OP_COMPLETION  Op = 2
	Op_OP_EMBED       Op = 3
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_CHAT",
		2: "OP_COMPLETION",
		3: "OP_EMBED",
	}
	Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_CHAT":        1,
		"OP_COMPLETION":  2,
		"OP_EMBED":       3,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_lcm_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_lcm_v1_scheduler_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

type Privacy int32

const (
	Privacy_PRIVACY_UNSPECIFIED Privacy = 0 // any node in the mesh
	Privacy_PRIVACY_LOCAL_ONLY  Privacy = 1 // only nodes tagged "trusted:home"
)

// Enum value maps for Privacy.
var (
	Privacy_name = map[int32]string{
		0: "PRIVACY_UNSPECIFIED",
		1: "PRIVACY_LOCAL_ONLY",
	}
	Privacy_value = map[string]int32{
		"PRIVACY_UNSPECIFIED": 0,
		"PRIVACY_LOCAL_ONLY":  1,
	}
)

func (x Privacy) Enum() *Privacy {
	p := new(Privacy)
	*p = x
	return p
}

func (x Privacy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Privacy) Descriptor() protoreflect.EnumDescriptor {
	return file_lcm_v1_scheduler_proto_enumTypes[1].Descriptor()
}

func (Privacy) Type() protoreflect.EnumType {
	return &file_lcm_v1_scheduler_proto_enumTypes[1]
}

func (x Privacy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Privacy.Descriptor instead.
func (Privacy) EnumDescriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

type NodeState int32

const (
	NodeState_NODE_STATE_UNSPECIFIED NodeState = 0
	NodeState_NODE_STATE_ALIVE       NodeState = 1
	NodeState_NODE_STATE_SUSPECT     NodeState = 2
	NodeState_NODE_STATE_DEAD        NodeState = 3
	NodeState_NODE_STATE_DRAINING    NodeState = 4
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNSPECIFIED",
		1: "NODE_STATE_ALIVE",
		2: "NODE_STATE_SUSPECT",
		3: "NODE_STATE_DEAD",
		4: "NODE_STATE_DRAINING",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNSPECIFIED": 0,
		"NODE_STATE_ALIVE":       1,
		"NODE_STATE_SUSPECT":     2,
		"NODE_STATE_DEAD":        3,
		"NODE_STATE_DRAINING":    4,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_lcm_v1_scheduler_proto_enumTypes[2].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_lcm_v1_scheduler_proto_enumTypes[2]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

type ScheduleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Op              Op                     `protobuf:"varint,3,opt,name=op,proto3,enum=lcm.v1.Op" json:"op,omitempty"`
	Privacy         Privacy                `protobuf:"varint,4,opt,name=privacy,proto3,enum=lcm.v1.Privacy" json:"privacy,omitempty"`
	PreferNode      string                 `protobuf:"bytes,5,opt,name=prefer_node,json=preferNode,proto3" json:"prefer_node,omitempty"`       // X-LCM-Prefer-Node; soft preference
	ExcludeNodes    []string               `protobuf:"bytes,6,rep,name=exclude_nodes,json=excludeNodes,proto3" json:"exclude_nodes,omitempty"` // failover: nodes that already failed this request
	EstimatedTokens uint32                 `protobuf:"varint,7,opt,name=estimated_tokens,json=estimatedTokens,proto3" json:"estimated_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScheduleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ScheduleRequest) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNSPECIFIED
}

func (x *ScheduleRequest) GetPrivacy() Privacy {
	if x != nil {
		return x.Privacy
	}
	return Privacy_PRIVACY_UNSPECIFIED
}

func (x *ScheduleRequest) GetPreferNode() string {
	if x != nil {
		return x.PreferNode
	}
	return ""
}

func (x *ScheduleRequest) GetExcludeNodes() []string {
	if x != nil {
		return x.ExcludeNodes
	}
	return nil
}

func (x *ScheduleRequest) GetEstimatedTokens() uint32 {
	if x != nil {
		return x.EstimatedTokens
	}
	return 0
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,2,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	ModelResident bool                   `protobuf:"varint,4,opt,name=model_resident,json=modelResident,proto3" json:"model_resident,omitempty"` // false ⇒ expect a cold start
	DecisionNs    uint64                 `protobuf:"varint,5,opt,name=decision_ns,json=decisionNs,proto3" json:"decision_ns,omitempty"`          // wall time the scheduler spent; feeds the <1 ms p99 target
	Candidates    []*Candidate           `protobuf:"bytes,6,rep,name=candidates,proto3" json:"candidates,omitempty"`                             // top-k for debugging / `meshctl explain`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ScheduleResponse) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *ScheduleResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScheduleResponse) GetModelResident() bool {
	if x != nil {
		return x.ModelResident
	}
	return false
}

func (x *ScheduleResponse) GetDecisionNs() uint64 {
	if x != nil {
		return x.DecisionNs
	}
	return 0
}

func (x *ScheduleResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	RejectedBy    string                 `protobuf:"bytes,3,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"` // empty if it passed all hard filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *Candidate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Candidate) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Candidate) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

type NodeView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *NodeInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Telemetry     *TelemetrySample       `protobuf:"bytes,2,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	State         NodeState              `protobuf:"varint,3,opt,name=state,proto3,enum=lcm.v1.NodeState" json:"state,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeView) Reset() {
	*x = NodeView{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeView) ProtoMessage() {}

func (x *NodeView) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeView.ProtoReflect.Descriptor instead.
func (*NodeView) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *NodeView) GetInfo() *NodeInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *NodeView) GetTelemetry() *TelemetrySample {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *NodeView) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNSPECIFIED
}

func (x *NodeView) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeView            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []*NodeView {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

type MeshModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResidentOn    []string               `protobuf:"bytes,2,rep,name=resident_on,json=residentOn,proto3" json:"resident_on,omitempty"`    // node_ids with weights loaded
	AvailableOn   []string               `protobuf:"bytes,3,rep,name=available_on,json=availableOn,proto3" json:"available_on,omitempty"` // node_ids with weights on disk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshModel) Reset() {
	*x = MeshModel{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshModel) ProtoMessage() {}

func (x *MeshModel) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshModel.ProtoReflect.Descriptor instead.
func (*MeshModel) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *MeshModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MeshModel) GetResidentOn() []string {
	if x != nil {
		return x.ResidentOn
	}
	return nil
}

func (x *MeshModel) GetAvailableOn() []string {
	if x != nil {
		return x.AvailableOn
	}
	return nil
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*MeshModel           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_lcm_v1_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lcm_v1_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_lcm_v1_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *ListModelsResponse) GetModels() []*MeshModel {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_lcm_v1_scheduler_proto protoreflect.FileDescriptor

const file_lcm_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x16lcm/v1/scheduler.proto\x12\x06lcm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11lcm/v1/node.proto\"\xfe\x01\n" +
	"\x0fScheduleRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1a\n" +
	"\x02op\x18\x03 \x01(\x0e2\n" +
	".lcm.v1.OpR\x02op\x12)\n" +
	"\aprivacy\x18\x04 \x01(\x0e2\x0f.lcm.v1.PrivacyR\aprivacy\x12\x1f\n" +
	"\vprefer_node\x18\x05 \x01(\tR\n" +
	"preferNode\x12#\n" +
	"\rexclude_nodes\x18\x06 \x03(\tR\fexcludeNodes\x12)\n" +
	"\x10estimated_tokens\x18\a \x01(\rR\x0festimatedTokens\"\xd9\x01\n" +
	"\x10ScheduleResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tgrpc_addr\x18\x02 \x01(\tR\bgrpcAddr\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12%\n" +
	"\x0emodel_resident\x18\x04 \x01(\bR\rmodelResident\x12\x1f\n" +
	"\vdecision_ns\x18\x05 \x01(\x04R\n" +
	"decisionNs\x121\n" +
	"\n" +
	"candidates\x18\x06 \x03(\v2\x11.lcm.v1.CandidateR\n" +
	"candidates\"[\n" +
	"\tCandidate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1f\n" +
	"\vrejected_by\x18\x03 \x01(\tR\n" +
	"rejectedBy\"\xc9\x01\n" +
	"\bNodeView\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.lcm.v1.NodeInfoR\x04info\x125\n" +
	"\ttelemetry\x18\x02 \x01(\v2\x17.lcm.v1.TelemetrySampleR\ttelemetry\x12'\n" +
	"\x05state\x18\x03 \x01(\x0e2\x11.lcm.v1.NodeStateR\x05state\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\x12\n" +
	"\x10ListNodesRequest\";\n" +
	"\x11ListNodesResponse\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.lcm.v1.NodeViewR\x05nodes\"\x13\n" +
	"\x11ListModelsRequest\"c\n" +
	"\tMeshModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vresident_on\x18\x02 \x03(\tR\n" +
	"residentOn\x12!\n" +
	"\favailable_on\x18\x03 \x03(\tR\vavailableOn\"?\n" +
	"\x12ListModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.lcm.v1.MeshModelR\x06models*F\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aOP_CHAT\x10\x01\x12\x11\n" +
	"\rOP_COMPLETION\x10\x02\x12\f\n" +
	"\bOP_EMBED\x10\x03*:\n" +
	"\aPrivacy\x12\x17\n" +
	"\x13PRIVACY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PRIVACY_LOCAL_ONLY\x10\x01*\x83\x01\n" +
	"\tNodeState\x12\x1a\n" +
	"\x16NODE_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_STATE_ALIVE\x10\x01\x12\x16\n" +
	"\x12NODE_STATE_SUSPECT\x10\x02\x12\x13\n" +
	"\x0fNODE_STATE_DEAD\x10\x03\x12\x17\n" +
	"\x13NODE_STATE_DRAINING\x10\x042\xd8\x01\n" +
	"\x10SchedulerService\x12=\n" +
	"\bSchedule\x12\x17.lcm.v1.ScheduleRequest\x1a\x18.lcm.v1.ScheduleResponse\x12@\n" +
	"\tListNodes\x12\x18.lcm.v1.ListNodesRequest\x1a\x19.lcm.v1.ListNodesResponse\x12C\n" +
	"\n" +
	"ListModels\x12\x19.lcm.v1.ListModelsRequest\x1a\x1a.lcm.v1.ListModelsResponseB3Z1github.com/sanj6y/compute-mesh/proto/lcm/v1;lcmv1b\x06proto3"

var (
	file_lcm_v1_scheduler_proto_rawDescOnce sync.Once
	file_lcm_v1_scheduler_proto_rawDescData []byte
)

func file_lcm_v1_scheduler_proto_rawDescGZIP() []byte {
	file_lcm_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_lcm_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lcm_v1_scheduler_proto_rawDesc), len(file_lcm_v1_scheduler_proto_rawDesc)))
	})
	return file_lcm_v1_scheduler_proto_rawDescData
}

var file_lcm_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lcm_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lcm_v1_scheduler_proto_goTypes = []any{
	(Op)(0),                       // 0: lcm.v1.Op
	(Privacy)(0),                  // 1: lcm.v1.Privacy
	(NodeState)(0),                // 2: lcm.v1.NodeState
	(*ScheduleRequest)(nil),       // 3: lcm.v1.ScheduleRequest
	(*ScheduleResponse)(nil),      // 4: lcm.v1.ScheduleResponse
	(*Candidate)(nil),             // 5: lcm.v1.Candidate
	(*NodeView)(nil),              // 6: lcm.v1.NodeView
	(*ListNodesRequest)(nil),      // 7: lcm.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 8: lcm.v1.ListNodesResponse
	(*ListModelsRequest)(nil),     // 9: lcm.v1.ListModelsRequest
	(*MeshModel)(nil),             // 10: lcm.v1.MeshModel
	(*ListModelsResponse)(nil),    // 11: lcm.v1.ListModelsResponse
	(*NodeInfo)(nil),              // 12: lcm.v1.NodeInfo
	(*TelemetrySample)(nil),       // 13: lcm.v1.TelemetrySample
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_lcm_v1_scheduler_proto_depIdxs = []int32{
	0,  // 0: lcm.v1.ScheduleRequest.op:type_name -> lcm.v1.Op
	1,  // 1: lcm.v1.ScheduleRequest.privacy:type_name -> lcm.v1.Privacy
	5,  // 2: lcm.v1.ScheduleResponse.candidates:type_name -> lcm.v1.Candidate
	12, // 3: lcm.v1.NodeView.info:type_name -> lcm.v1.NodeInfo
	13, // 4: lcm.v1.NodeView.telemetry:type_name -> lcm.v1.TelemetrySample
	2,  // 5: lcm.v1.NodeView.state:type_name -> lcm.v1.NodeState
	14, // 6: lcm.v1.NodeView.last_seen:type_name -> google.protobuf.Timestamp
	6,  // 7: lcm.v1.ListNodesResponse.nodes:type_name -> lcm.v1.NodeView
	10, // 8: lcm.v1.ListModelsResponse.models:type_name -> lcm.v1.MeshModel
	3,  // 9: lcm.v1.SchedulerService.Schedule:input_type -> lcm.v1.ScheduleRequest
	7,  // 10: lcm.v1.SchedulerService.ListNodes:input_type -> lcm.v1.ListNodesRequest
	9,  // 11: lcm.v1.SchedulerService.ListModels:input_type -> lcm.v1.ListModelsRequest
	4,  // 12: lcm.v1.SchedulerService.Schedule:output_type -> lcm.v1.ScheduleResponse
	8,  // 13: lcm.v1.SchedulerService.ListNodes:output_type -> lcm.v1.ListNodesResponse
	11, // 14: lcm.v1.SchedulerService.ListModels:output_type -> lcm.v1.ListModelsResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_lcm_v1_scheduler_proto_init() }
func file_lcm_v1_scheduler_proto_init() {
	if File_lcm_v1_scheduler_proto != nil {
		return
	}
	file_lcm_v1_node_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lcm_v1_scheduler_proto_rawDesc), len(file_lcm_v1_scheduler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lcm_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_lcm_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_lcm_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_lcm_v1_scheduler_proto_msgTypes,
	}.Build()
	File_lcm_v1_scheduler_proto = out.File
	file_lcm_v1_scheduler_proto_goTypes = nil
	file_lcm_v1_scheduler_proto_depIdxs = nil
}
